apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: degraded-timeout-svc
  namespace: demo
spec:
  selector:
    app: missing-backend
  ports:
    - port: 80
      targetPort: 80
