apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: demo
spec:
  hard:
    requests.cpu: "1500"
    requests.memory: "2Gi"
    pods: "10"
---
apiVersion: v1
kind: Pod
metadata:
  name: pending-quota-demo
  namespace: demo
  labels:
    app: pending-quota-demo
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "1000"
          memory: "128Mi"
