apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-probe-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-probe-demo
  template:
    metadata:
      labels:
        app: oom-probe-demo
    spec:
      containers:
        - name: app
          image: python:3.12-alpine
          command:
            - python
            - -c
            - |
              data = []
              while True:
                  data.append("x" * 1024 * 1024)
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "80Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
