apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
  namespace: demo
  labels:
    app: pending-demo
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "1000"
          memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noise-frontend
  namespace: demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: noise-frontend
  template:
    metadata:
      labels:
        app: noise-frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noise-batch
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: noise-batch
  template:
    metadata:
      labels:
        app: noise-batch
    spec:
      containers:
        - name: batch
          image: busybox:1.36
          command: ["sh", "-c", "sleep 3600"]
