apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  namespace: demo
  labels:
    app: oom-demo
spec:
  containers:
    - name: memory-hog
      image: python:3.12-alpine
      command:
        - python
        - -c
        - |
          data = []
          while True:
              data.append("x" * 1024 * 1024)
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "80Mi"
